services:
  ow-who-said-it-frontend:
    image: ghcr.io/${GH_OWNER}/ow-who-said-it-frontend:${TAG}
    container_name: ow-who-said-it-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8082}:8082"